// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rE2qLwquIRVgU1GNp9dY2D-Yb73gG1c',
    appId: '1:151141982970:web:4b2e121fc6d53b4fee9f43',
    messagingSenderId: '151141982970',
    projectId: 'oceanic-test-77f80',
    authDomain: 'oceanic-test-77f80.firebaseapp.com',
    storageBucket: 'oceanic-test-77f80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRh50PORKg7bnyJs7Ny3xqpS6RujL-FJ8',
    appId: '1:151141982970:android:6aaf2c256eeacde9ee9f43',
    messagingSenderId: '151141982970',
    projectId: 'oceanic-test-77f80',
    storageBucket: 'oceanic-test-77f80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVCmyOgWGZURfn4fXRkxRQbKcjz3EotE',
    appId: '1:151141982970:ios:039852517a2c7400ee9f43',
    messagingSenderId: '151141982970',
    projectId: 'oceanic-test-77f80',
    storageBucket: 'oceanic-test-77f80.firebasestorage.app',
    iosBundleId: 'com.oceanichealth.oceanic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVCmyOgWGZURfn4fXRkxRQbKcjz3EotE',
    appId: '1:151141982970:ios:039852517a2c7400ee9f43',
    messagingSenderId: '151141982970',
    projectId: 'oceanic-test-77f80',
    storageBucket: 'oceanic-test-77f80.firebasestorage.app',
    iosBundleId: 'com.oceanichealth.oceanic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1rE2qLwquIRVgU1GNp9dY2D-Yb73gG1c',
    appId: '1:151141982970:web:807958160096d1e2ee9f43',
    messagingSenderId: '151141982970',
    projectId: 'oceanic-test-77f80',
    authDomain: 'oceanic-test-77f80.firebaseapp.com',
    storageBucket: 'oceanic-test-77f80.firebasestorage.app',
  );
}